FROM almalinux:9
LABEL author="shabeena" \
      course="devops" \
      description="this is docker practice"
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
    