ARG version
FROM almalinux:${version:-8}
#RUN cat/etc/*release
CMD [ "sleep","100" ]
ARG course=docker
ARG trainer=shabeena
ARG duration=120hrs
ENV duration=${duration}
RUN echo "course is :${course},trainer is :${trainer}, duration is :${duration}"
CMD [ "sleep", "100"]